name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o deploy toda vez que houver push na branch main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Garante que as versões sejam as mesmas do seu yarn.lock

      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: "andresjesse"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          yarn deploy
